apiVersion: v1
kind: ConfigMap
metadata: 
  name: pgbouncer-config
  namespace: dbspace
data:
  userlist.txt: |
    "postgres" "timescaledb@pg"

  pgbouncer.ini: |
    [databases]
    postgresdb = host=db-service port=5432 user=postgres

    [pgbouncer]
    listen_addr = 0.0.0.0
    listen_port = 5432
    unix_socket_dir =
    user = postgres
    auth_file = /etc/pgbouncer/userlist.txt
    auth_type = scram-sha-256
    pool_mode = transaction
    ignore_startup_parameters = extra_float_digits

    # Log settings
    admin_users = postgres

    # Connection sanity checks, timeouts
    server_reset_query = DISCARD ALL

    # TLS settings

    # Dangerous timeouts
    ################## end file ##################
