apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-service
  namespace: dbspace
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
    nodePort: 32588
  selector:
    app: pgbouncer
  type: NodePort
