kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: cubestore-pvc
    namespace: cubejs

spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
